### ISSUE TITLE
add onlyOwner lockUnlock() function

### ISSUE THREAD

**Issue by Matlemad** [Bisonai/sbt-contracts#21]
SBT could be turned temporarily transferrable by Owner, or Governor with a quorum and a majority.

use cases are: GDPR European Union. An SBT holder has the Right to Oblivion, to be delisted.

**Comment by bayram98** [comment]
@Matlemad Thanks for raising issue about the allowing transfer for specific condition. Yes, it could very good feature to give users right to be delisted from the SBT. 

However, your approach of make users able to transfer SBT, it might be misleading. Users might transfer, sell or give away `SBT`'s to any user, which I think against of bound principle. 
 
If we would like to give a right to `SBT` holders to delist, or burn their `SBT`, with our latest change, we added `burn` functionality where function can be called by `ownerOf` `SBT`. 
[https://github.com/Bisonai/sbt-contracts/pull/23](https://github.com/Bisonai/sbt-contracts/pull/23)

**Comment by martinkersner** [comment]
Closing this issue as explained by @bayram98. If there is any need for this, please reopen it.
